/**
 * Report reader
 *
 * Reads the questions out of the Markdown report the GrillMyCode action posts
 * as an issue (formatReport in src/report.js, renderQuestions in
 * src/postprocess.js).
 *
 * The issue text is untrusted: anyone who can write to the repository can edit
 * it. Nothing here evaluates it, and a report that does not fit the expected
 * shape yields fewer questions, or null, never an exception.
 *
 * Each question comes back in the shape of the instructor repository's
 * questions.json (buildQuestionsJson in src/delivery/instructor-repo.js), less
 * the fields a student's report never carries:
 *
 *   { number, broader, snippets: [{ file, start_line, end_line, language, code }],
 *     question, answer? }
 *
 * `answer` is present only when the instructor set include_answers.
 *
 * Since layout version 1 the issue also carries a hidden comment under its
 * heading (questionsComment in src/report.js):
 *
 *   <!-- gmc:questions {"version":1,"headSha":"…","questions":[…]} -->
 *
 * It lists each question's number, whether it is a broader one, and its
 * snippets' files and lines. When it is there, those are taken from it, and
 * the Markdown supplies the rest: the question's text, the code and the
 * answer. When its version is newer than ISSUE_LAYOUT_VERSION, nothing is
 * read. An issue posted before the comment existed is read from the Markdown
 * alone.
 */

import { ISSUE_LAYOUT_VERSION } from './constants.js';

/**
 * One piece of code a question shows, with where it is in the repository.
 *
 * @typedef {object} Snippet
 * @property {string} file
 * @property {number} start_line
 * @property {number} end_line
 * @property {string} language
 * @property {string} code
 */

/**
 * A question, as the report gives it. An answer key's adds `distractors`
 * (parseAnswerKey in instructor/answer-key.js).
 *
 * @typedef {object} Question
 * @property {number} number
 * @property {boolean} broader
 * @property {Snippet[]} snippets
 * @property {string} question
 * @property {string} [answer]
 * @property {string[]} [distractors]
 */

/**
 * A report this extension reads, as parseReport describes it.
 *
 * @typedef {object} Report
 * @property {string} baseSha
 * @property {string} headSha
 * @property {string} [headCommit]
 * @property {string | null} branch
 * @property {string | null} tag
 * @property {string[]} files
 * @property {Question[]} questions
 * @property {boolean} truncated
 * @property {undefined} [needsUpdate]
 */

/**
 * A report in a layout newer than this extension reads.
 *
 * @typedef {{ needsUpdate: true, questions: Question[] }} NewerReport
 */

/**
 * The hidden data comment of a layout this extension reads.
 *
 * @typedef {object} ReportData
 * @property {number} version
 * @property {string} headSha
 * @property {{ number: number, broader: boolean, snippets: Pick<Snippet, 'file' | 'start_line' | 'end_line'>[] }[]} questions
 */

/**
 * The hidden data comment of a newer layout: its version, and nothing else.
 *
 * @typedef {{ version: number, questions?: undefined }} NewerReportData
 */

/** Zero-width space, which the action puts after `@` and `#` to stop GitHub linking them. */
const ZWSP = '​';

const HEADING = /^## .*GrillMyCode\s*$/;
const COMMITS = /^> \*\*Commits reviewed:\*\* `([0-9a-f]+)` → `([0-9a-f]+)`/;
const BRANCH = /^> \*\*Branch:\*\* `(.+)`\s*$/;
const TAG = /^> \*\*Submission tag:\*\* `([^`]+)`/;
const FILES = /^> \*\*Code Files Assessed:\*\* (.*)$/;
const RULE = /^---\s*$/;
const QUESTION_LABEL = /^\*\*Question (\d+):\*\*\s*$/;
const BROADER_HEADING = /^## Broader Questions\s*$/;
const CAPTION = /^\*\*`(.+)`\*\*, lines? (\d+)(?:–(\d+))?\s*$/;
const FENCE_OPEN = /^(`{3,})([^`\s]*)\s*$/;
const ANSWER_LABEL = /^\*\*Answer:\*\*\s*$/;
const FOOTER = /^_Generated by \*\*GrillMyCode\*\*/;
const CUT_NOTICE = /^> \[!WARNING\]\s*$/;
const DATA_COMMENT = /^<!-- gmc:questions (.*) -->\s*$/;
const FULL_SHA = /^[0-9a-f]{40,64}$/;

/** @param {any} value */
const isCount = (value) => Number.isInteger(value) && value >= 0;

/**
 * @param {ReportData | NewerReportData} data
 * @returns {data is NewerReportData}
 */
const isNewer = (data) => data.version > ISSUE_LAYOUT_VERSION;

/**
 * Reads the hidden data comment: the first line that is one, wherever it is,
 * since a later layout may move it. Returns `{ version }` alone for a version
 * this extension does not know, whose other fields may mean something else,
 * and null when there is no comment or it is not what the action writes.
 *
 * @param {string[]} lines
 * @returns {ReportData | NewerReportData | null}
 */
function readData(lines) {
  const line = lines.find((candidate) => DATA_COMMENT.test(candidate));
  if (!line) return null;
  let data;
  try {
    data = JSON.parse(line.match(DATA_COMMENT)?.[1] ?? '');
  } catch {
    return null;
  }
  if (!Number.isInteger(data?.version) || data.version < 1) return null;
  if (data.version > ISSUE_LAYOUT_VERSION) return { version: data.version };

  const sound =
    typeof data.headSha === 'string' &&
    FULL_SHA.test(data.headSha) &&
    Array.isArray(data.questions) &&
    data.questions.every(
      (/** @type {any} */ q) =>
        isCount(q?.number) &&
        typeof q.broader === 'boolean' &&
        Array.isArray(q.snippets) &&
        q.snippets.every(
          (/** @type {any} */ s) =>
            typeof s?.file === 'string' && isCount(s.start_line) && isCount(s.end_line),
        ),
    );
  return sound ? data : null;
}

/**
 * Puts the data's facts over what the Markdown gave for the same question:
 * whether it is a broader one, and each snippet's file and lines. A question
 * the data does not list, or lists with another number of snippets, has been
 * edited by hand and is left as the Markdown has it.
 *
 * @param {Question[]} questions
 * @param {ReportData} data
 * @returns {Question[]}
 */
function withData(questions, data) {
  const listed = new Map(data.questions.map((q) => [q.number, q]));
  return questions.map((question) => {
    const facts = listed.get(question.number);
    if (!facts || facts.snippets.length !== question.snippets.length) return question;
    return {
      ...question,
      broader: facts.broader,
      snippets: question.snippets.map((snippet, i) => ({
        ...snippet,
        file: facts.snippets[i].file,
        start_line: facts.snippets[i].start_line,
        end_line: facts.snippets[i].end_line,
      })),
    };
  });
}

/**
 * Undoes what the action does to a line of prose on its way into the issue:
 * the bold it wraps around a question's text, and the zero-width space that
 * defuses a mention or an issue reference. Inline code spans are left as they
 * are, as the action leaves them.
 *
 * @param {string} text
 */
function plainProse(text) {
  return text
    .split(/(`[^`]+`)/)
    .map((part, i) =>
      i % 2 === 1
        ? part
        : part.replace(/\*\*/g, '').replaceAll(`@${ZWSP}`, '@').replaceAll(`#${ZWSP}`, '#'),
    )
    .join('')
    .trim();
}

/**
 * Reads the report's header block, or returns null when it is not a report.
 *
 * @param {string[]} lines
 */
function readHeader(lines) {
  const first = lines.findIndex((line) => line.trim() !== '');
  if (first === -1 || !HEADING.test(lines[first])) return null;

  const end = lines.findIndex((line, i) => i > first && RULE.test(line));
  if (end === -1) return null;

  /** @type {Pick<Report, 'baseSha' | 'headSha' | 'branch' | 'tag' | 'files'>} */
  const header = { baseSha: '', headSha: '', branch: null, tag: null, files: [] };
  for (const line of lines.slice(first + 1, end)) {
    const commits = line.match(COMMITS);
    if (commits) [, header.baseSha, header.headSha] = commits;
    const branch = line.match(BRANCH);
    if (branch) header.branch = branch[1];
    const tag = line.match(TAG);
    if (tag) header.tag = tag[1];
    const files = line.match(FILES);
    if (files) header.files = [...files[1].matchAll(/`([^`]+)`/g)].map((m) => m[1]);
  }
  // Every report names the commits it reviewed. Without them this is some
  // other issue that happens to share the heading.
  return header.headSha ? { header, bodyStart: end + 1 } : null;
}

/**
 * Parses a questions issue's body.
 *
 * Returns null when the text is not a GrillMyCode report. Otherwise:
 *
 *   { baseSha, headSha, headCommit?, branch, tag, files, questions, truncated }
 *
 * `baseSha` and `headSha` are the short SHAs the report prints. `headCommit`
 * is the full SHA behind `headSha`, present when the issue carries its hidden
 * data. `branch` is null for the default branch, which the report does not
 * name, and `tag` is null unless a submission tag started the run. `truncated`
 * is true when the report stops before its footer — the action cuts an issue
 * that would pass GitHub's size limit — so the last questions are missing.
 *
 * An issue in a layout newer than this extension reads comes back as
 * `{ needsUpdate: true, questions: [] }` and nothing else: its Markdown may
 * have changed too, so none of it is read.
 *
 * @param {unknown} body
 * @returns {Report | NewerReport | null}
 */
export function parseReport(body) {
  if (typeof body !== 'string') return null;
  const lines = body.split(/\r?\n/);
  const data = readData(lines);
  if (data && isNewer(data)) return { needsUpdate: true, questions: [] };
  const read = readHeader(lines);
  if (!read) return null;

  /** @type {Question[]} */
  const questions = [];
  /** @type {Question | null} */
  let current = null;
  let broader = false;
  /** @type {{ file: string, start: number, end: number } | null} */
  let caption = null;
  let awaitingAnswer = false;
  let sawFooter = false;
  // Whether the rule just passed closed a question, which a cut notice then
  // shows to be the one the cut landed in.
  let ruleClosedQuestion = false;

  const finish = () => {
    const complete = Boolean(current?.question);
    if (current && complete) questions.push(current);
    current = null;
    caption = null;
    awaitingAnswer = false;
    return complete;
  };

  for (let i = read.bodyStart; i < lines.length; i++) {
    const line = lines[i];

    if (FOOTER.test(line)) {
      sawFooter = true;
      break;
    }
    if (RULE.test(line)) {
      ruleClosedQuestion = finish();
      continue;
    }
    if (CUT_NOTICE.test(line)) {
      // The action cut the report at a fixed length and closed it with a rule
      // and this notice, so the question before the rule may stop mid-sentence.
      if (ruleClosedQuestion) questions.pop();
      break;
    }
    if (BROADER_HEADING.test(line)) {
      broader = true;
      continue;
    }
    const label = line.match(QUESTION_LABEL);
    if (label) {
      finish();
      ruleClosedQuestion = false;
      current = { number: Number(label[1]), broader, snippets: [], question: '' };
      continue;
    }
    if (!current) continue;

    const captioned = line.match(CAPTION);
    if (captioned && !current.question) {
      const start = Number(captioned[2]);
      caption = { file: captioned[1], start, end: Number(captioned[3] ?? start) };
      continue;
    }

    const fence = line.match(FENCE_OPEN);
    if (fence && !current.question) {
      // The action picks a fence longer than any run of backticks in the code,
      // so the first line that is exactly the fence closes it.
      const close = lines.findIndex((l, j) => j > i && l.trimEnd() === fence[1]);
      if (close === -1) break; // cut off inside a snippet
      current.snippets.push({
        file: caption?.file ?? '',
        start_line: caption?.start ?? 0,
        end_line: caption?.end ?? 0,
        language: fence[2],
        code: lines.slice(i + 1, close).join('\n'),
      });
      caption = null;
      i = close;
      continue;
    }

    if (ANSWER_LABEL.test(line)) {
      awaitingAnswer = Boolean(current.question);
      continue;
    }
    if (line.trim() === '') continue;

    if (awaitingAnswer) {
      current.answer = plainProse(line.replace(/^- /, ''));
      awaitingAnswer = false;
    } else if (!current.question) {
      current.question = plainProse(line);
    }
  }
  if (sawFooter) finish();

  return {
    ...read.header,
    ...(data ? { headCommit: data.headSha } : {}),
    questions: data ? withData(questions, data) : questions,
    truncated: !sawFooter,
  };
}
