/**
 * Report Formatter
 *
 * Pure Markdown assembly — takes the generated questions and metadata and
 * returns the final report string. No side effects, no I/O.
 */

import { GIT_SHA_SHORT_LENGTH } from './constants.js';

/**
 * Assembles the full Markdown assessment report.
 *
 * The optional `studentLogin`, `sourceRepo`, and `allChangedFiles` parameters
 * are used when generating the instructor copy of the report:
 *   - studentLogin     — GitHub login of the assessed student
 *   - sourceRepo       — full "owner/repo" name of the student's repository
 *   - allChangedFiles  — unfiltered list of all files changed since the base
 *                        SHA; when provided it replaces the filtered `files`
 *                        list in the report metadata
 */
export function formatReport({
  questions,
  files,
  baseSha,
  headSha,
  provider,
  model,
  branchName,
  assignmentContextFiles,
  contextSummary,
  studentLogin,
  sourceRepo,
  allChangedFiles,
  pdfUrl,
}) {
  const date = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
  const shortBase = baseSha.substring(0, GIT_SHA_SHORT_LENGTH);
  const shortHead = headSha.substring(0, GIT_SHA_SHORT_LENGTH);
  const displayFiles = allChangedFiles ?? files;
  const fileList = displayFiles.map((f) => `\`${f}\``).join(', ');

  const isDefaultBranch = !branchName || branchName === 'main' || branchName === 'master';
  const branchNote = isDefaultBranch ? '' : `> **Branch:** \`${branchName}\`\n`;

  const contextNote =
    assignmentContextFiles && assignmentContextFiles.length > 0
      ? `> **Assignment Context:** ${assignmentContextFiles.map((f) => `\`${f}\``).join(', ')}\n`
      : '';

  const instructorContextNote = contextSummary ? `> **Instructor Note:** ${contextSummary}\n` : '';

  const studentNote = studentLogin ? `\n> **Student:** \`${studentLogin}\`\n` : '';
  const sourceRepoNote = sourceRepo ? `> **Repository:** \`${sourceRepo}\`\n` : '';

  const pdfBadge = pdfUrl
    ? [
        `[![Download as PDF](https://img.shields.io/badge/Download_as_PDF-DC143C?style=for-the-badge&logo=adobeacrobatreader&logoColor=white)](${pdfUrl})`,
        '',
      ]
    : [];

  return [
    '## GrillMyCode',
    '',
    ...pdfBadge,
    `> **Generated:** ${date}`,
    studentNote,
    sourceRepoNote,
    `> **Commits reviewed:** \`${shortBase}\` → \`${shortHead}\``,
    branchNote,
    `> **Code Files Assessed:** ${fileList}`,
    contextNote,
    instructorContextNote,
    '---',
    '',
    questions,
    '',
    '---',
    '',
    `_Generated by **GrillMyCode** · ${model} via ${provider}${process.env.GITHUB_ACTION_REF ? ` · ${process.env.GITHUB_ACTION_REF}` : ''}_`,
  ].join('\n');
}

/**
 * Assembles the verbatim copy of the model's reply, with a short provenance
 * header above it.
 *
 * The reply is embedded unfenced and unaltered. Wrapping it in a code fence
 * would read better in the rendered view, but the reply contains fences of its
 * own — a wrapper could be closed early by the model's own text and corrupt the
 * very copy this file exists to preserve. Verbatim bytes are the point; use
 * GitHub's raw view to see markers and whitespace as the model emitted them.
 */
export function formatRawOutput({
  rawOutput,
  baseSha,
  headSha,
  provider,
  model,
  studentLogin,
  sourceRepo,
}) {
  const date = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
  const shortBase = baseSha.substring(0, GIT_SHA_SHORT_LENGTH);
  const shortHead = headSha.substring(0, GIT_SHA_SHORT_LENGTH);

  const studentNote = studentLogin ? `> **Student:** \`${studentLogin}\`\n` : '';
  const sourceRepoNote = sourceRepo ? `> **Repository:** \`${sourceRepo}\`\n` : '';

  return [
    '## GrillMyCode — Raw AI Output',
    '',
    '> [!NOTE]',
    "> Everything below the rule is the model's reply exactly as received, before",
    '> any renumbering, truncation, summary extraction or formatting. It is kept',
    '> for diagnosis and is not the assessment — see `questions.md` for that.',
    '',
    `> **Generated:** ${date}`,
    studentNote,
    sourceRepoNote,
    `> **Commits reviewed:** \`${shortBase}\` → \`${shortHead}\``,
    `> **Model:** \`${model}\` via ${provider}`,
    '',
    '---',
    '',
    rawOutput,
  ].join('\n');
}
