/**
 * Report Formatter
 *
 * Pure Markdown assembly — takes the generated questions and metadata and
 * returns the final report string. No side effects, no I/O.
 */

import { GIT_SHA_SHORT_LENGTH } from './constants.js';

/**
 * Assembles the full Markdown assessment report.
 *
 * The optional `studentLogin`, `sourceRepo`, and `allChangedFiles` parameters
 * are used when generating the instructor copy of the report:
 *   - studentLogin     — GitHub login of the assessed student
 *   - sourceRepo       — full "owner/repo" name of the student's repository
 *   - allChangedFiles  — unfiltered list of all files changed since the base
 *                        SHA; when provided it replaces the filtered `files`
 *                        list in the report metadata
 */
export function formatReport({
  questions,
  files,
  baseSha,
  headSha,
  truncated,
  provider,
  model,
  branchName,
  assignmentContextFiles,
  contextSummary,
  studentLogin,
  sourceRepo,
  allChangedFiles,
  pdfUrl,
}) {
  const date = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
  const shortBase = baseSha.substring(0, GIT_SHA_SHORT_LENGTH);
  const shortHead = headSha.substring(0, GIT_SHA_SHORT_LENGTH);
  const displayFiles = allChangedFiles ?? files;
  const fileList = displayFiles.map((f) => `\`${f}\``).join(', ');
  const truncNote = truncated
    ? '> **⚠️ Note:** The content was truncated — questions may not cover all changes.\n'
    : '';

  const isDefaultBranch = !branchName || branchName === 'main' || branchName === 'master';
  const branchNote = isDefaultBranch ? '' : `> **Branch:** \`${branchName}\`\n`;

  const contextNote =
    assignmentContextFiles && assignmentContextFiles.length > 0
      ? `> **Assignment Context:** ${assignmentContextFiles.map((f) => `\`${f}\``).join(', ')}\n`
      : '';

  const instructorContextNote = contextSummary ? `> **Instructor Note:** ${contextSummary}\n` : '';

  const studentNote = studentLogin ? `\n> **Student:** \`${studentLogin}\`\n` : '';
  const sourceRepoNote = sourceRepo ? `> **Repository:** \`${sourceRepo}\`\n` : '';

  const pdfLine = pdfUrl ? [`---`, ``, `[📄 Download PDF](${pdfUrl})`, ``] : [];

  return [
    '## GrillMyCode',
    '',
    `> **Generated:** ${date}`,
    studentNote,
    sourceRepoNote,
    `> **Commits reviewed:** \`${shortBase}\` → \`${shortHead}\``,
    branchNote,
    `> **Code Files Assessed:** ${fileList}`,
    contextNote,
    instructorContextNote,
    truncNote,
    '---',
    '',
    questions,
    '',
    ...pdfLine,
    '---',
    '',
    `<sub>Generated by <b>GrillMyCode</b> · ${model} via ${provider}${process.env.GITHUB_ACTION_REF ? ` · ${process.env.GITHUB_ACTION_REF}` : ''}</sub>`,
  ].join('\n');
}
