import { readFileSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { describe, expect, it } from 'vitest';
import { findQuestionIssues } from '../src/shared/issues.js';
import { parseReport } from '../src/shared/report.js';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'fixtures');

/** Every fixture case under extensions/fixtures/, current layout and kept ones alike. */
const cases = readdirSync(FIXTURES, { recursive: true, withFileTypes: true })
  .filter((entry) => entry.isFile() && entry.name === 'body.md')
  .map((entry) => ({
    name: entry.parentPath.slice(FIXTURES.length + 1),
    issue: JSON.parse(readFileSync(join(entry.parentPath, 'issue.json'), 'utf-8')),
    body: readFileSync(join(entry.parentPath, 'body.md'), 'utf-8'),
    expected: JSON.parse(readFileSync(join(entry.parentPath, 'expected.json'), 'utf-8')),
  }));

describe('reading the fixtures', () => {
  it('finds some', () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  it.each(cases)('$name: recognizes the issue', ({ issue, body, expected }) => {
    const [found] = findQuestionIssues([{ number: 7, ...issue, body }]);
    expect(found.group).toEqual(expected.group);
  });

  it.each(cases)('$name: reads the report', ({ body, expected }) => {
    expect(parseReport(body)).toEqual({ ...expected.report, questions: expected.questions });
  });

  // GitHub stores an issue edited in the browser with CRLF line endings.
  it.each(cases)('$name: reads the report with CRLF line endings', ({ body, expected }) => {
    expect(parseReport(body.replace(/\n/g, '\r\n'))).toEqual({
      ...expected.report,
      questions: expected.questions,
    });
  });
});

const body = cases.find((c) => c.name.endsWith('default-branch')).body;
const feature = cases.find((c) => c.name.endsWith('feature-branch')).body;

describe('parseReport', () => {
  it.each([
    ['undefined', undefined],
    ['an empty body', ''],
    ['an ordinary issue', '## Bug\n\nThe cart total is wrong.\n\n---\n\nSteps to reproduce…'],
    ['the heading alone', '## GrillMyCode\n\n---\n\n**Question 1:**\n\nWhy?\n'],
  ])('returns null for %s', (_name, text) => {
    expect(parseReport(text)).toBeNull();
  });

  it('keeps a rule and a fence inside a snippet as code', () => {
    const [first] = parseReport(feature).questions;
    expect(first.snippets).toHaveLength(1);
    expect(first.snippets[0].code).toContain('```bash');
    expect(first.snippets[0].code).toContain('\n---\n');
    expect(first.question).toBe('What does `printHelp` write when it is called with no argument?');
  });

  it('restores the @ and # the action defused', () => {
    const fourth = parseReport(body).questions[3];
    expect(fourth.question).toBe(
      'Which line would change if issue #12 asked for a rate tagged @deprecated to be skipped?',
    );
  });

  it('marks a report with no footer as truncated', () => {
    const cut = body.slice(0, body.indexOf('_Generated by'));
    const report = parseReport(cut);
    expect(report.truncated).toBe(true);
    expect(report.questions).toHaveLength(5);
  });

  // The action cuts an over-long issue at a fixed length, then closes it with
  // a rule and a notice, so the cut can land anywhere in a question.
  const notice = '\n\n---\n\n> [!WARNING]\n> The assessment was too long to display in full here.';

  it('drops the question a cut landed in the text of', () => {
    const at = body.indexOf('would change if issue');
    const report = parseReport(body.slice(0, at) + notice);
    expect(report.truncated).toBe(true);
    expect(report.questions.map((q) => q.number)).toEqual([1, 2, 3]);
  });

  it('drops the question a cut landed in a snippet of', () => {
    const at = body.indexOf('const rate = RATES', body.indexOf('**Question 4:**'));
    const report = parseReport(body.slice(0, at) + notice);
    expect(report.questions.map((q) => q.number)).toEqual([1, 2, 3]);
  });

  it('keeps the earlier questions when a cut lands before any of the next', () => {
    const at = body.indexOf('**Question 4:**') + '**Question 4:**'.length;
    const report = parseReport(body.slice(0, at) + notice);
    expect(report.questions.map((q) => q.number)).toEqual([1, 2, 3]);
  });

  it('reads nothing from text added after the footer', () => {
    const edited = `${body}\n\n---\n\n**Question 99:**\n\n**Is this one real?**\n`;
    expect(parseReport(edited).questions.map((q) => q.number)).toEqual([1, 2, 3, 4, 5]);
  });

  it('never takes a later line for the question', () => {
    const edited = body.replace(
      '**Question 2:**',
      '**Question 2:**\n\n**First text.**\n\n**Second text.**',
    );
    expect(parseReport(edited).questions[1].question).toBe('First text.');
  });
});
